# Car parameters

car:
  mu: 0.523
  m: 3.47
  g: 9.81
  l_f: 0.158
  l_r: 0.17
  
# limits 
lims:
  max_v: 7
  max_a: 8.5
  max_steer: 0.4
  max_d_dot: 3.2
  dis_scale: 0.5

map:
  # name: "race_track"
  name: "porto"
  # name: "torino"
  # name: "berlin"
  # name: "levine"
  ext: ".png"
  obs_size: 0.6
  n_obs: 8
  # obs_buf: 3
  # end:
  #   x: 3
  #   y: 14
map_name: porto

sim:
  timestep: 0.01
  update_f: 10
  beams: 10

pp:
  lookahead: 1.5
  v_gain: 0.9
  force_f: 0.8

nn:
  h: 200